services:
  order-postgres:
    image: ${POSTGRES_IMAGE_NAME}
    container_name: order-postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - order-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - services-network

networks:
  services-network:
    external: true

volumes:
  order-postgres-data: