// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateOrderOperation     OperationName = "CreateOrder"
	GetOrderByIDOperation    OperationName = "GetOrderByID"
	OrderCancelByIdOperation OperationName = "OrderCancelById"
	PayOrderByIdOperation    OperationName = "PayOrderById"
)
