// Code generated by ogen, DO NOT EDIT.
package order_v1

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderByIDRes interface {
	getOrderByIDRes()
}

type OrderCancelByIdRes interface {
	orderCancelByIdRes()
}

type PayOrderByIdRes interface {
	payOrderByIdRes()
}
