// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateOrder implements CreateOrder operation.
//
// Создаёт новый заказ на основе выбранных
// пользователем деталей.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByID implements GetOrderByID operation.
//
// Возвращает информацию о заказе.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByID(ctx context.Context, params GetOrderByIDParams) (r GetOrderByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderCancelById implements OrderCancelById operation.
//
// Отменяет заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) OrderCancelById(ctx context.Context, params OrderCancelByIdParams) (r OrderCancelByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrderById implements PayOrderById operation.
//
// Проводит оплату ранее созданного заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrderById(ctx context.Context, req *PayOrderRequest, params PayOrderByIdParams) (r PayOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
