// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateOrder implements CreateOrder operation.
	//
	// Создаёт новый заказ на основе выбранных
	// пользователем деталей.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderByID implements GetOrderByID operation.
	//
	// Возвращает информацию о заказе.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByID(ctx context.Context, params GetOrderByIDParams) (GetOrderByIDRes, error)
	// OrderCancelById implements OrderCancelById operation.
	//
	// Отменяет заказ.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	OrderCancelById(ctx context.Context, params OrderCancelByIdParams) (OrderCancelByIdRes, error)
	// PayOrderById implements PayOrderById operation.
	//
	// Проводит оплату ранее созданного заказа.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrderById(ctx context.Context, req *PayOrderRequest, params PayOrderByIdParams) (PayOrderByIdRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
