// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/H1dEx/ms-rocket/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, userUUID, partUUIDs
func (_m *OrderService) CreateOrder(ctx context.Context, userUUID string, partUUIDs []string) (model.Order, error) {
	ret := _m.Called(ctx, userUUID, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (model.Order, error)); ok {
		return rf(ctx, userUUID, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) model.Order); ok {
		r0 = rf(ctx, userUUID, partUUIDs)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, userUUID, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - partUUIDs []string
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, userUUID interface{}, partUUIDs interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userUUID, partUUIDs)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, userUUID string, partUUIDs []string)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 model.Order, _a1 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, string, []string) (model.Order, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) GetOrderByID(ctx context.Context, orderUUID string) (model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type OrderService_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderService_Expecter) GetOrderByID(ctx interface{}, orderUUID interface{}) *OrderService_GetOrderByID_Call {
	return &OrderService_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, orderUUID)}
}

func (_c *OrderService_GetOrderByID_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderService_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetOrderByID_Call) Return(_a0 model.Order, _a1 error) *OrderService_GetOrderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrderByID_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *OrderService_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// OrderCancelById provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) OrderCancelById(ctx context.Context, orderUUID string) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for OrderCancelById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_OrderCancelById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderCancelById'
type OrderService_OrderCancelById_Call struct {
	*mock.Call
}

// OrderCancelById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderService_Expecter) OrderCancelById(ctx interface{}, orderUUID interface{}) *OrderService_OrderCancelById_Call {
	return &OrderService_OrderCancelById_Call{Call: _e.mock.On("OrderCancelById", ctx, orderUUID)}
}

func (_c *OrderService_OrderCancelById_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderService_OrderCancelById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_OrderCancelById_Call) Return(_a0 error) *OrderService_OrderCancelById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_OrderCancelById_Call) RunAndReturn(run func(context.Context, string) error) *OrderService_OrderCancelById_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrderById provides a mock function with given fields: ctx, orderUUID, paymentMethod
func (_m *OrderService) PayOrderById(ctx context.Context, orderUUID string, paymentMethod model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrderById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) (string, error)); ok {
		return rf(ctx, orderUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) string); ok {
		r0 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_PayOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrderById'
type OrderService_PayOrderById_Call struct {
	*mock.Call
}

// PayOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - paymentMethod model.PaymentMethod
func (_e *OrderService_Expecter) PayOrderById(ctx interface{}, orderUUID interface{}, paymentMethod interface{}) *OrderService_PayOrderById_Call {
	return &OrderService_PayOrderById_Call{Call: _e.mock.On("PayOrderById", ctx, orderUUID, paymentMethod)}
}

func (_c *OrderService_PayOrderById_Call) Run(run func(ctx context.Context, orderUUID string, paymentMethod model.PaymentMethod)) *OrderService_PayOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.PaymentMethod))
	})
	return _c
}

func (_c *OrderService_PayOrderById_Call) Return(transactionUUID string, err error) *OrderService_PayOrderById_Call {
	_c.Call.Return(transactionUUID, err)
	return _c
}

func (_c *OrderService_PayOrderById_Call) RunAndReturn(run func(context.Context, string, model.PaymentMethod) (string, error)) *OrderService_PayOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
