services:
  inventory-mongo:
    image: ${MONGO_IMAGE_NAME}
    container_name: inventory-mongo
    env_file: .env
    ports:
      - "${EXTRERNAL_MONGO_PORT}:27017"
    volumes:
      - inventory-mongo-data:/data/db
    networks:
      - services-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  services-network:
    external: true

volumes:
  inventory-mongo-data: